FROM andi91/rdesktop_skretch_without 

RUN \
  sudo apt-get update &&\
  sudo apt-get install -y wget &&\
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - &&\
  echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list &&\
  sudo apt-get update &&\
  sudo apt install -y google-chrome-stable &&\
  sudo mkdir -p "/opt/google/chrome/extensions" &&\
  sudo bash -c 'echo "{" > "/opt/google/chrome/extensions/ifibfemgeogfhoebkmokieepdoobkbpo.json"' &&\
  sudo bash -c 'echo "  \"external_update_url\": \"https://clients2.google.com/service/update2/crx\"" >> "/opt/google/chrome/extensions/ifibfemgeogfhoebkmokieepdoobkbpo.json"' &&\
  sudo bash -c 'echo "}" >> "/opt/google/chrome/extensions/ifibfemgeogfhoebkmokieepdoobkbpo.json"' &&\
  sudo echo Added \"/opt/google/chrome/extensions/ifibfemgeogfhoebkmokieepdoobkbpo.json\" ["2Captcha Solver"]

#  mkdir /config/.config/google-chrome/ &&\
#  touch "/config/.config/google-chrome/First Run" &&\

# ports and volumes
EXPOSE 3389
#VOLUME /config